[package]
name = "gba-core"
version = "0.1.0"
authors = ["Takeshi Masumoto <take44444.general@gmail.com>"]
edition = "2021"

[lib]
name = "gba_core"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
